<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC23eDYC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC23eDYC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC23eDYC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC23eDYC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC23eDYC\App_KernelDevDebugContainer([
    'container.build_hash' => 'C23eDYC',
    'container.build_id' => 'c5a0e966',
    'container.build_time' => 1585153530,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC23eDYC');
